# Configuration file for LastCall v1.3
# Options for the /lastcall command
lastcall:
    # Sets the default song to play when using /lastcall
    # Default value is stal. accepts disc names or ID numbers
    Song: stal
    # Sets the default time to count down before stopping the
    # server, in seconds. Default value is 30.
    time: 30

# Options for the /play command
play: 
    # This is a list of players who won't hear songs when
    # someone uses /play on them. When using /play on
    # themselves, though, they'll still hear it.
    exempt: []
    