name: LastCall
main: com.github.kaitoyuuki.LastCall.LCMain
version: 1.8MD
commands:
    lc:
        description: base command for lastcall.
        usage: /<command> {reload}
        aliases: last
    play:
        description: plays a music disc
    lastcall:
        description: plays the last call song and notifies users how long before shutdown.
        usage: /<command> [time] [disc]
    testcall:
        description: simulates /lastcall for the user who used the command
        usage: /<command> [time] [disc]
    playlist:
        description: show playlists
        usage: /<command>
Permissions:
    lastcall.*:
        description: Gives access to all LastCall commands
        children:
            lastcall.reload: true
            lastcall.lastcall: true
            lastcall.testcall: true
            lastcall.play: true
            lastcall.play.others: true
            lastcall.playall: true
            lastcall.playlist: true
            lastcall.playlist.op: true
    lastcall.play.*:
        description: Gives access to play music discs for anyone
        children:
            lastcall.play: true
            lastcall.play.others: true
            lastcall.playall: true
    lastcall.playlist.op:
        description: Gives access to editing all playlists
        default: op
        children:
            lastcall.playlist: true
            lastcall.playlist.create: true
    lastcall.playlist.create:
        description: allows you to create, delete, and modify playlists
        default: op
    lastcall.lc:
        description: base command for LastCall.
        default: op
    lastcall.lastcall:
        description: allows you to start the shutdown timer
        default: op
    lastcall.testcall:
        description: allows you to see a demo of /lastcall
        default: true
    lastcall.play:
        description: lets you play a music disc for yourself
        default: true
    lastcall.play.others:
        description: allows you to set the currently playing disc for others
        default: op
    lastcall.playall:
        description: allows you to play a music disc for everyone
        default: op